version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    # env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_NAME: sidekiqrails_development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: shark
      DATABASE_HOST: database
      REDIS_HOST: redis
    labels:
      kompose.service.type: LoadBalancer

  database:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: shark
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.1
    ports: 
      - "6379:6379"

  exporter:
    image:  strech/sidekiq-prometheus-exporter
    depends_on:
      - redis
    ports: 
      - "9292:9292"
    environment:
      REDIS_URL: redis://C02XD2USJG5M:6379/0

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app      
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    # env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_NAME: sidekiqrails_development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: shark
      DATABASE_HOST: database
      REDIS_HOST: redis
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data: