apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: app
  type: LoadBalancer
status:
  loadBalancer: {}
