apiVersion: batch/v1
kind: Job
metadata:
  name: db-create
  labels:
    app.kubernetes.io/name: app-create
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-create
    spec:
      containers:
      - name: main
        command: ["rails"]
        args: ["db:create"]
        env:
          - name: DATABASE_HOST
            value: C02XD2USJG5M
          - name: DATABASE_NAME
            value: sidekiqrails_development
          - name: DATABASE_PASSWORD
            value: shark
          - name: DATABASE_USER
            value: postgres
          - name: RAILS_ENV
            value: development
          - name: REDIS_HOST
            value: C02XD2USJG5M
        image: sidekiqrails_app:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Never