apiVersion: batch/v1
kind: Job
metadata:
  name: app-db-create
  labels:
    app.kubernetes.io/name: app-db-create
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-db-create
    spec:
      containers:
      - name: main
        command: ["rails"]
        args: ["db:create"]
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DATABASE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        image: sidekiqrails_app:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Never