apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: exporter
  name: exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sidekiqrails-default: "true"
        io.kompose.service: exporter
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: REDIS_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: REDIS_URL
              value: redis://$(REDIS_HOST):$(REDIS_PORT)/0
          image: strech/sidekiq-prometheus-exporter
          name: exporter
          ports:
            - containerPort: 9292
              hostPort: 9292
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
