apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq
  name: sidekiq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sidekiq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sidekiqrails-default: "true"
        io.kompose.service: sidekiq
    spec:
      containers:
        - command:
            - ./entrypoints/sidekiq-entrypoint.sh
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DATABASE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: REDIS_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: sidekiqrails_sidekiq:latest
          imagePullPolicy: IfNotPresent
          name: sidekiq
          resources: {}
      restartPolicy: Always
status: {}
